import $ from 'jquery';
global.jQuery = $;
global.$ = $;
let validate = require('./validate.js');
// let slick = require('./slick');
//let slickmin = require('./slick.min.js');
//let jquerymin = require('./jquery-3.4.1.min.js');
//require("./jquery-3.4.1.min.js");
let popup = require('./popup.js');
let popupfun = require('./popup-fun.js');